name: prettify
on:
  pull_request:
    branches: [main]
permissions:
  actions: write
  contents: write
  pull-requests: write
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Run Prettier
        run: |
          npm install
          npm run format
      - name: Commit and push changes back to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          changed_files=$(git diff --cached --name-only)
          if [[ -n "$changed_files" ]]; then
            echo "The following files were modified:"
            echo "$changed_files"
            git commit -m "fix: prettier formatting"
            git push origin ${{ github.head_ref }}
          else
            echo "No changes to commit."
          fi
